Update thirteenth Github action
Add Failure Step

diff --git a/.github/workflows/action_13.yml b/.github/workflows/action_13.yml
--- a/.github/workflows/action_13.yml
+++ b/.github/workflows/action_13.yml
@@ -9,6 +9,9 @@ jobs:
       # - name: First Step
       #   # run: sleep 30
       #   run: exit 1
+      - name: Failure Step
+        id: error-step
+        run: exit 1
       - name: Runs on Canceled
         if: ${{ cancelled() }}
         run: echo "Runs on Canceled"
@@ -19,7 +22,7 @@ jobs:
         if: ${{ success() }}
         run: echo "Runs on Success"
       - name: Runs on Failure
-        if: ${{ failure() }}
+        if: ${{ failure() && steps.error-step.conclusion == 'failure'}}
         run: echo "Runs on Failure"
   job-two:
     runs-on: ubuntu-latest
